#define PROJ_SCREENMODE TASMODE
#define PROJ_FPS 30
#define PROJ_HIGH_RAM HIGH_RAM_ON
#define PROJ_ENABLE_SOUND 1
#define PROJ_AUD_FREQ 8000
//#define PROJ_FILE_STREAMING
#define PROJ_MAX_SPRITES 32
#define PROJ_TILE_H 8
#define PROJ_TILE_W 8
#define PROJ_DEVELOPER_MODE 0
#define MAX_TILE_COUNT 256
#define PROJ_LINE_FILLERS TAS::NOPFiller,TAS::NOPFiller,TAS::NOPFiller,TAS::NOPFiller
