//Automatically generated by editor
#pragma once

namespace PTAD
{
  namespace Resources
  {
    //Battle resources
    extern const uint32_t backgrounds[];
    extern const uint32_t enemies[];
    extern const uint8_t enemyNames[];
    extern const uint8_t numEnemies;
    //Dialog resources
    extern const uint8_t messages[];
    extern const uint8_t messageSizes[];
    constexpr int battleAgilityUp = 0;
    constexpr int battleAttackUp = 1;
    constexpr int battleBerserk1 = 2;
    constexpr int battleBerserk2 = 3;
    constexpr int battleBerserk3 = 4;
    constexpr int battleBerserkAttack = 5;
    constexpr int battleCastSpell = 6;
    constexpr int battleChooseAction = 7;
    constexpr int battleCleansed = 8;
    constexpr int battleCriticalHit = 9;
    constexpr int battleDamageDealt = 10;
    constexpr int battleDamageTakenBegin = 11;
    constexpr int battleDamageTakenEnd = 12;
    constexpr int battleDefeat = 13;
    constexpr int battleDefenseUp = 14;
    constexpr int battleExperienceGained = 15;
    constexpr int battleFight = 16;
    constexpr int battleFocus1 = 17;
    constexpr int battleFocus2 = 18;
    constexpr int battleFocus3 = 19;
    constexpr int battleGoldEarned = 20;
    constexpr int battleInflictHaste = 21;
    constexpr int battleInflictPoison = 22;
    constexpr int battleInflictPoisonFail = 23;
    constexpr int battleInflictSlow = 24;
    constexpr int battleInflictSlowFail = 25;
    constexpr int battleLevelUp = 26;
    constexpr int battleMagicUp = 27;
    constexpr int battleMiss = 28;
    constexpr int battlePoisonBegin = 29;
    constexpr int battleRecoveredAmount = 30;
    constexpr int battleRemoveBerserk = 31;
    constexpr int battleRemovePoison = 32;
    constexpr int battleRemoveSlow = 33;
    constexpr int battleRunFail = 34;
    constexpr int battleRunImpossible = 35;
    constexpr int battleRunSuccess = 36;
    constexpr int battleSkillLearned = 37;
    constexpr int battleSurpriseAttack = 38;
    constexpr int battleUseItem = 39;
    constexpr int battleUseSkill = 40;
    constexpr int menuDialogTest = 41;
    //Game resources
    struct StatGrowth
    {
      uint32_t start;
      float base;
      float exponent;
    };
    extern const StatGrowth hpGrowth;
    extern const StatGrowth mpGrowth;
    extern const StatGrowth attackGrowth;
    extern const StatGrowth defenseGrowth;
    extern const StatGrowth agilityGrowth;
    extern const StatGrowth magicGrowth;
    extern const StatGrowth experienceGrowth;
    extern const uint8_t skillLearned[99];
    constexpr uint32_t getStatForLevel(uint8_t level, const StatGrowth &growth)
    {
      return growth.start + (uint32_t)(growth.base * pow(level, growth.exponent));
    }
    //Global resources
    struct Item
    {
      uint8_t name[8];
      uint8_t description[24];
      uint16_t price;
    };
    struct EquipmentStats
    {
      int8_t stats[4];
      uint16_t spellResistance;
      int8_t statusResistance[2];
    };
    extern const uint32_t tilesets[];
    extern const uint32_t tiledataFiles[];
    extern const uint8_t playerSprite[];
    extern const uint8_t cursor[];
    extern const uint8_t statusIcons[];
    extern const Item items[8][16];
    extern const Item skills[16];
    extern const Item spells[16];
    extern const EquipmentStats equipmentStats[6][16];
    //Audio resources
    extern const uint32_t music[];
    extern const uint32_t sfx[];
    constexpr int music_battle = 0;
    constexpr int music_battleBoss = 1;
    constexpr int music_battleFinal = 2;
    constexpr int music_characterRevived = 3;
    constexpr int music_discovery = 4;
    constexpr int music_docks = 5;
    constexpr int music_dungeon = 6;
    constexpr int music_fields = 7;
    constexpr int music_gameOver = 8;
    constexpr int music_goodMorning = 9;
    constexpr int music_goodNight = 10;
    constexpr int music_inn = 11;
    constexpr int music_joinParty = 12;
    constexpr int music_labyrinth = 13;
    constexpr int music_levelUp = 14;
    constexpr int music_machineRoom = 15;
    constexpr int music_mainTheme = 16;
    constexpr int music_mysticIsle = 17;
    constexpr int music_princess = 18;
    constexpr int music_royalCourt = 19;
    constexpr int music_shop = 20;
    constexpr int music_tavern = 21;
    constexpr int music_temple = 22;
    constexpr int music_town = 23;
    constexpr int music_winBattle = 24;
    constexpr int music_winBattleBig = 25;
    constexpr int music_winBattleBoss = 26;
    constexpr int music_winBattleFinal = 27;
    constexpr int sfx_berserk = 0;
    constexpr int sfx_cancel = 1;
    constexpr int sfx_claw = 2;
    constexpr int sfx_coin = 3;
    constexpr int sfx_cursor = 4;
    constexpr int sfx_dialog = 5;
    constexpr int sfx_dream = 6;
    constexpr int sfx_droplet = 7;
    constexpr int sfx_gate = 8;
    constexpr int sfx_getItem = 9;
    constexpr int sfx_heal = 10;
    constexpr int sfx_hit = 11;
    constexpr int sfx_invalid = 12;
    constexpr int sfx_miss = 13;
    constexpr int sfx_poison = 14;
    constexpr int sfx_punch = 15;
    constexpr int sfx_quake = 16;
    constexpr int sfx_run = 17;
    constexpr int sfx_rune = 18;
    constexpr int sfx_select = 19;
    constexpr int sfx_slow = 20;
    constexpr int sfx_sword = 21;
    constexpr int sfx_useitem = 22;
  };
};
